//! Helix distributed log server.
//!
//! This crate provides the gRPC server implementation for Helix,
//! exposing the Write, Read, and Metadata APIs to clients.
//!
//! Supports two protocols:
//! - `--protocol grpc` (default): Native Helix gRPC API
//! - `--protocol kafka`: Kafka wire protocol compatibility

#![deny(unsafe_code)]
#![warn(missing_docs)]

/// Allocator statistics endpoint (jemalloc stats over TCP).
pub mod alloc_stats;
/// Kafka admin gRPC service (kafkaadmin.Resources on port 8090).
pub mod admin_grpc;
/// Controller partition for cluster metadata coordination.
pub mod controller;
/// Dedicated Raft groups for Kafka consumer group offset storage.
pub mod offset_group;
mod error;
/// Group ID mapping for topic/partition to Raft group.
pub mod group_map;
mod grpc;
/// Kafka wire protocol support.
pub mod kafka;
/// Partition storage (in-memory and durable).
pub mod partition_storage;
/// Idempotent producer state tracking.
pub mod producer_state;
/// Helix service implementation.
pub mod service;
/// Partition storage implementations.
pub mod storage;
/// Vote state persistence for Raft consensus.
pub mod vote_store;

pub mod generated {
    //! Generated protobuf types.
    //!
    //! This module contains code auto-generated by prost/tonic from protobuf definitions.
    //! Clippy warnings are suppressed since we don't own this generated code.
    #![allow(clippy::all)]
    #![allow(clippy::pedantic)]
    #![allow(clippy::nursery)]
    include!("generated/helix.v1.rs");
}

/// Generated kafkaadmin protobuf types (admin API).
pub mod generated_admin {
    #![allow(clippy::all)]
    #![allow(clippy::pedantic)]
    #![allow(clippy::nursery)]
    #![allow(missing_docs)]
    include!("generated/kafkaadmin.rs");
}

pub use error::{ServerError, ServerResult};
pub use service::{HelixService, ProductionHelixService};
