//! Helix distributed log server.
//!
//! This crate provides the gRPC server implementation for Helix,
//! exposing the Write, Read, and Metadata APIs to clients.
//!
//! Supports two protocols:
//! - `--protocol grpc` (default): Native Helix gRPC API
//! - `--protocol kafka`: Kafka wire protocol compatibility

#![deny(unsafe_code)]
#![warn(missing_docs)]

mod error;
/// Kafka wire protocol support.
pub mod kafka;
mod service;
/// Partition storage implementations.
pub mod storage;

pub mod generated {
    //! Generated protobuf types.
    //!
    //! This module contains code auto-generated by prost/tonic from protobuf definitions.
    //! Clippy warnings are suppressed since we don't own this generated code.
    #![allow(clippy::all)]
    #![allow(clippy::pedantic)]
    #![allow(clippy::nursery)]
    include!("generated/helix.v1.rs");
}

pub use error::{ServerError, ServerResult};
pub use service::HelixService;
